[project]
name = "avenys"
version = "4.3.0"
entry = "tests/mod.mr"

[build]
compiler = "mire"
profile = "debug"
opt-level = 0
runtime = "full"

[paths]
sources = "code"
tests = "tests"
output = "tests/log/bin"
cache = "tests/log/bin/.cache"

[dependencies]
kioto = { path = "../kioto", version = "2.4.7" }
mire = { path = "../mire", version = "0.0.7" }
sqlite = { path = "../sqlite", version = "0.1.0" }

[c]
libs = ["sqlite3"]
sources = ["../sqlite/native/sqlite_bridge.c"]

[macros]
ensure_answer = "tests/Macros/Custom/mod.mire"
assert = "../mire/core/macros/assert.mire"
assert_eq = "../mire/core/macros/checks.mire"
assert_ne = "../mire/core/macros/checks.mire"
dbg = "../mire/core/macros/dbg.mire"
trace_i64 = "../mire/core/macros/checks.mire"
panic = "../mire/core/macros/panic.mire"
unreachable = "../mire/core/macros/panic.mire"
["owl@lock"]
version = "3"
